---
# tasks file for nodejs
- name: Download Node.js
  get_url: >
    url=http://nodejs.org/dist/v{{ nodejs_version }}/node-v{{ nodejs_version }}-{{ nodejs_os }}-{{ nodejs_arch }}.tar.gz
    dest=/usr/local/src/node-v{{ nodejs_version }}-{{ nodejs_os }}-{{ nodejs_arch }}.tar.gz
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  when:

- name: Extract and install Node.js
  unarchive: src=/usr/local/src/node-v{{ nodejs_version }}-{{ nodejs_os }}-{{ nodejs_arch }}.tar.gz
             dest=/usr/local
             copy=no
             creates=/usr/local/node-v{{ nodejs_version }}-{{ nodejs_os }}-{{ nodejs_arch }}

- name: Move to generic path
  shell: mv /usr/local/node-v{{ nodejs_version }}-{{ nodejs_os }}-{{ nodejs_arch }} /usr/local/node

- name: Symlink Node.js into /usr/local/bin
  file: >
    src=/usr/local/node/bin/{{ item }}
    dest={{ nodejs_symlink_path }}/{{ item }}
    state=link
  with_items:
    - node
    - npm
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: Ensure git is installed for npm deps
  yum:
    name: git
    state: latest
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: Determine what version of NPM is installed
  shell: "{{ nodejs_symlink_path }}/npm --version"
  register: installed_npm_version

- name: Upgrade NPM
  shell: "/usr/local/node/bin/npm install --global --force npm@{{ nodejs_npm_version }}"
  when: installed_npm_version.stdout != nodejs_npm_version
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
